In [3]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
len(alphabets)

26

In [4]:
int2char = {idx:char for idx,char in enumerate(alphabets)}
int2char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [5]:
char2int = {char:idx for idx,char in int2char.items()}
char2int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [6]:
seq_length = 1
x = []
y = []
for i in range(len(alphabets)-seq_length):
    seq_in = [alphabets[i]]
    seq_out = alphabets[i+1]
    x += [[char2int[seq_in[0]]]]
    y += [char2int[seq_out]]
    print(seq_in,'->',seq_out)

['A'] -> B
['B'] -> C
['C'] -> D
['D'] -> E
['E'] -> F
['F'] -> G
['G'] -> H
['H'] -> I
['I'] -> J
['J'] -> K
['K'] -> L
['L'] -> M
['M'] -> N
['N'] -> O
['O'] -> P
['P'] -> Q
['Q'] -> R
['R'] -> S
['S'] -> T
['T'] -> U
['U'] -> V
['V'] -> W
['W'] -> X
['X'] -> Y
['Y'] -> Z


In [7]:
x

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [8]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [9]:
from keras.utils import to_categorical

In [10]:
y_new = to_categorical(y)


In [11]:
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [12]:
import numpy as np

In [13]:
x = np.reshape(x,(25,1,1))

In [16]:
x=x/25

In [17]:
x 

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

In [23]:
len(x),len(y_new)

(25, 25)

In [18]:
### Build the model
from keras.models import Sequential
from keras.layers import Dense,LSTM

In [20]:
model = Sequential()
model.add(Dense(25,input_shape=(1,1),activation='relu'))
model.add(LSTM(128))
model.add(Dense(26,activation='softmax'))

In [25]:
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])

In [26]:
model.fit(x,y_new,epochs=1000,batch_size=1)

Epoch 1/1000
25/25 [==============================] - 3s 6ms/step - loss: 3.2699 - accuracy: 0.0000e+00
Epoch 2/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.2578 - accuracy: 0.0400
Epoch 3/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.2533 - accuracy: 0.0400
Epoch 4/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.2479 - accuracy: 0.0400
Epoch 5/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.2417 - accuracy: 0.0400
Epoch 6/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.2339 - accuracy: 0.0400
Epoch 7/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.2217 - accuracy: 0.0400
Epoch 8/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.2078 - accuracy: 0.0400
Epoch 9/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.1876 - accuracy: 0.0400
Epoch 10/1000
25/25 [==============================] - 0s 6ms/step - loss: 3.1635 - accuracy: 0.

In [52]:
new = 'F'
new = char2int[new]/25

In [54]:
new = np.array([[[new]]])

In [55]:
np.argmax(model.predict(new))

1/1 [==============================] - 0s 26ms/step


6

In [63]:
seq_length = 3
x = []
y = []
for i in range(len(alphabets)-seq_length):
    seq_in = [alphabets[i:i+seq_length]]
    seq_out = alphabets[i+seq_length]
    x.append([char2int[char] for char in seq_in[0]])
    y.append(char2int[seq_logout])
    print(seq_in,'->',seq_out)

['ABC'] -> D
['BCD'] -> E
['CDE'] -> F
['DEF'] -> G
['EFG'] -> H
['FGH'] -> I
['GHI'] -> J
['HIJ'] -> K
['IJK'] -> L
['JKL'] -> M
['KLM'] -> N
['LMN'] -> O
['MNO'] -> P
['NOP'] -> Q
['OPQ'] -> R
['PQR'] -> S
['QRS'] -> T
['RST'] -> U
['STU'] -> V
['TUV'] -> W
['UVW'] -> X
['VWX'] -> Y
['WXY'] -> Z


In [64]:
x

[[0, 1, 2],
 [1, 2, 3],
 [2, 3, 4],
 [3, 4, 5],
 [4, 5, 6],
 [5, 6, 7],
 [6, 7, 8],
 [7, 8, 9],
 [8, 9, 10],
 [9, 10, 11],
 [10, 11, 12],
 [11, 12, 13],
 [12, 13, 14],
 [13, 14, 15],
 [14, 15, 16],
 [15, 16, 17],
 [16, 17, 18],
 [17, 18, 19],
 [18, 19, 20],
 [19, 20, 21],
 [20, 21, 22],
 [21, 22, 23],
 [22, 23, 24]]

In [69]:
np.reshape(x,(23,1,3))

array([[[ 0,  1,  2]],

       [[ 1,  2,  3]],

       [[ 2,  3,  4]],

       [[ 3,  4,  5]],

       [[ 4,  5,  6]],

       [[ 5,  6,  7]],

       [[ 6,  7,  8]],

       [[ 7,  8,  9]],

       [[ 8,  9, 10]],

       [[ 9, 10, 11]],

       [[10, 11, 12]],

       [[11, 12, 13]],

       [[12, 13, 14]],

       [[13, 14, 15]],

       [[14, 15, 16]],

       [[15, 16, 17]],

       [[16, 17, 18]],

       [[17, 18, 19]],

       [[18, 19, 20]],

       [[19, 20, 21]],

       [[20, 21, 22]],

       [[21, 22, 23]],

       [[22, 23, 24]]])

In [70]:
y

[3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [ ]:
x= np.reshape(x,(len(x),seq_length,1))
x = x/25
print('Input Shape',x.shape)

model = Sequential()
